### ISSUE TITLE
macos doit.sh doesn't work

### ISSUE THREAD

**Issue by qichao-arlo-wang** [EIE2-IAC-Labs/Lab4-Reduced-RISC-V#10]
<img width="405" alt="Screenshot 2024-11-21 at 19 15 34" src="https://github.com/user-attachments/assets/03ebc754-7086-4f3c-90d5-7442cb0ad347">

in doit.sh file `cd $SCRIPT_DIR` should be changed to `cd $TEST_FOLDER` to ensure the script works as intended

**Comment by saturn691** [comment]
Going to close this issue… relative paths work better (normally you tab to autocomplete in terminal)
